require 'faker'

tip_data = [
  { text: 'Understand your appliances better.', details: 'Learn how to estimate what it costs to operate your appliances and how much energy they consume.'},
  { text: 'Close your exterior doors and windows tightly when the AC is on.', details: ''},
  { text: 'Turn off your kitchen and bathroom vent fans when not in use.', details: ''},
  { text: 'Open interior doors so that cooled air flows freely throughout your home.', details: ''},
  { text: 'Decorate for a cooler home', details: 'Hang light-colored curtains that allow light to enter a room while blocking some of the sun’s rays, and use light-colored paint to reflect heat.'},
  { text: 'Install more ceiling fans.', details: 'Because the breeze of a fan can make you feel three to four degrees cooler, you can raise that thermostat and still stay comfortable.'},
  { text: 'Install a programmable thermostat to adjust your temperature during the day.', details: ''},
  { text: 'Insulate your walls.', details: 'Use injected foam insulation to help you save energy by keeping hot outside air from seeping through porous block walls – check with your local building supply company for details.'},
  { text: 'Replace standard bulbs with LEDs.', details: ''},
  { text: 'Use motion-detector lights for your outdoor lighting.', details: ''},
  { text: 'Make your lamps more efficient.', details: 'Select light-colored or opaque lamp shades. Place lamps in corners so they reflect light from two walls.'},
  { text: 'Pull the plug on that second fridge located in the hot garage or utility room.', details: ''},
  { text: 'Check your refrigerator seals.', details: 'Repair refrigerator door seals if you feel cold air around the closed door or if moisture is collecting.'},
  { text: 'Keep your freezer full.', details: 'A full freezer uses less energy than an empty one. For maximum savings, consider filling your freezer with gallon containers of water.'},
  { text: "Wash and dry several loads at once.", details: "That way your dryer isn't completely cooled down when it heats up for the next load."},
  { text: 'Clean the dryer lint filter before every load.', details: ''}, 
  { text: 'Eliminate "hot spots" in your home.', details: 'Try High-performance windows, solar window screens and qualified window films.'},
  { text: 'Avoid energy vampires.' , details: 'Even when they’re turned off, home electronics in “standby” mode use energy to power features like clock displays.'},
  { text: 'Unplug battery chargers when not charging.', details: 'Many chargers draw power continuously, even when the device is not plugged into the charger.'},
  { text: 'Use power strips.', details: 'Plug electronics into a power strip, then turn the strip off when not in use to save in energy costs.' + "\n" + 'Also try advanced power strips for even more efficiency.'},
  { text: 'Grill out more often during the summer.', details: 'Using the oven in the heat of summer forces your AC to work harder, which raises your energy bill.'},
  { text: 'Keep water below 120 degrees.', details: ''},
  { text: 'Install low-flow fixtures on your shower and faucets.', details: ''},
  { text: 'Insulate hot water pipes.', details: ''},
  { text: 'Keep your AC 78 degrees or higher.', details: ''},
  { text: 'Replace your old light bulbs with LEDs.', details: ''},
  { text: 'Consider going solar.', details: ''},
  { text: 'Hang your clothing to dry.', details: 'Dress clothing in particular will look better when air dried.'},
  { text: 'Upgrade to a new energy efficient refrigerator.', details: ''},
  { text: 'Keep your heat down.', details: 'Keep the heat to 68 degrees or lower when home and 55-60 degrees when away sleeping. You can save 1-2\% on heating costs for every degree you turn down the thermostat.'},
  { text: 'Check for and plug air leaks.', details: ''},
  { text: 'Upgrade your furnace and replace oil with gas.', details: ''},
  { text: "Shut down your computer when you are not using it.", details: "On Windows, select 'Power Saver'. On Mac, select 'Energy Saver'."},
  { text: "Use the vent fan following your shower.", details: "Keeping the A/C off and going au natural feels good on your skin and is better for your energy usage."},
  { text: "Turn off 'heat dry' following your dish washing.", details: "Allowing those dishes to air dry will save you 15\% on your dishwasher energy costs."},
  { text: "Install solar powered lights in your garden.", details: "Give your plants a glow and save energy and money on artificial lights."},
  { text: "Get more people to sign up to the challenge to increase the impact you are creating!", details: ''},
]

tips ||= tip_data.map { |tip| Tip.create(tip) }
